Fix/nex 147 windows separator fix for local externals
oat-sa/tao-item-runner-fe pull request #4
Opened 2019-06-19 11:22 UTC by btamas

Jira: https://oat-sa.atlassian.net/browse/NEX-147

Test on Windows:
`npm run prepare`
`npm run test`

2019-06-19 15:11 UTC, jsconan requested changes
Almost work, but there are still some places where to filter the path.
In fact, every time a path is returned by the system, and is used to create a namespace, it should be filtered.

2019-06-20 04:51 UTC, btamas commented
> Almost work, but there are still some places where to filter the path.
> In fact, every time a path is returned by the system, and is used to create a namespace, it should be filtered.

It is working for me. Could you please show me where is the problem?

2019-06-20 07:27 UTC, jsconan approved these changes
Looks good indeed. I rechecked and it is working fine.

2019-06-20 08:43 UTC, krampstudio approved these changes

2019-06-20 09:05 UTC, merged